name: Install and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: pip install -e . -r dev-requirements.txt
      - name: Run test suite
        run: tox
