name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: "Release"
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest

      - name: "Checkout Codebase"
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3

      - name: "Install Nix"
        if: ${{ steps.release.outputs.release_created }}
        uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=channel:nixos-stable
          extra_nix_config: "system-features = benchmark, big-parallel, nixos-test, uid-range, kvm"

      - name: "Cleanup Directory"
        if: ${{ steps.release.outputs.release_created }}
        run: rm -Rf dist/

      - name: "Build Artifacts"
        if: ${{ steps.release.outputs.release_created }}
        run: nix-shell --run "python -m build"

      - name: "Pre-Upload Check"
        if: ${{ steps.release.outputs.release_created }}
        run: nix-shell --run "twine check dist/*"

      - name: "Upload"
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
