name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: "Release"
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest

      - name: "Checkout Codebase"
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
