name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["python310", "python311"]

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v1

      - name: Install Nix
        uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=channel:nixos-stable
          extra_nix_config: "system-features = benchmark, big-parallel, nixos-test, uid-range, kvm"

      - name: Run Tests
        run: nix-shell --argstr python ${{ matrix.python-version }} --run tox
